import tkinter as tk
window = tk.Tk()
window.geometry('600x700')
window.title('Register Form')
window.minsize(600, 700)
window.maxsize(600, 700)
window.configure(background='light blue',padx=10, pady=10)
first_name_label=tk.Label(window, text='First Name')
first_name = tk.Entry()
last_name_label=tk.Label(window, text='Last Name')
last_name = tk.Entry()
middle_label=tk.Label(window, text='Middle Name')
middle_name = tk.Entry()
gender_label=tk.Label(window, text='Gender')
gender = tk.Listbox()
employee_label = tk.Label(window, text='Employee Name')
employment_status=tk.IntVar()
employment_status.set(0)
note_label=tk.Label(window, text='Notes')
note = tk.Text()
register =tk.Button()
cancel = tk.Button()
# place items on the window grid
first_name_label.grid(row=0, column=0)
first_name.grid(row=0, column=1)
last_name_label.grid(row=1, column=0)
last_name.grid(row=1, column=1)
middle_label.grid(row=2, column=0)
middle_name.grid(row=2, column=1)
gender_label.grid(row=3, column=0)
gender.grid(row=3, column=1)
employee_label.grid(row=4, column=0)

window.mainloop()
